#!/usr/bin/env sh
# やばいですね

sudo yabai --load-sa

source ~/.config/yabai/appconfig.sh

# -----------------------
# yabai Settings
# -----------------------

# Global Settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                float
yabai -m config window_opacity               off
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.85

yabai -m config window_border              on
yabai -m config window_border_width        4
yabai -m config active_window_border_color 0xfff38ba8
# yabai -m config normal_window_border_color 0xff6c7086
yabai -m config window_animation_duration  0.1

yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# Space Settings
yabai -m config layout                       bsp
yabai -m config top_padding                  11
yabai -m config bottom_padding               11
yabai -m config left_padding                 11
yabai -m config right_padding                11
yabai -m config window_gap                   12

# External Bar
yabai -m config external_bar                 all:49:0
# yabai -m config external_bar main:35:0
# yabai -m config external_bar main:0:35

# -----------------------
# Signals
# -----------------------
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_resized action="sketchybar --trigger window_focus"

# yabai -m signal --add event=mission_control_exit action='echo "refresh" | nc -U /tmp/yabai-indicator.socket'
# yabai -m signal --add event=display_added action='echo "refresh" | nc -U /tmp/yabai-indicator.socket'
# yabai -m signal --add event=display_removed action='echo "refresh" | nc -U /tmp/yabai-indicator.socket'
# yabai -m signal --add event=window_created action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
# yabai -m signal --add event=window_destroyed action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
# yabai -m signal --add event=window_focused action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
# yabai -m signal --add event=window_moved action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
# yabai -m signal --add event=window_resized action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
# yabai -m signal --add event=window_minimized action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
# yabai -m signal --add event=window_deminimized action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'