#!/usr/bin/env sh
# やばいですね

sudo yabai --load-sa

source ~/.config/yabai/appconfig.sh

# -----------------------
# yabai Settings
# -----------------------

# Global Settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               on
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.85

yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
# yabai -m config mouse_modifier               fn
# yabai -m config mouse_action1                move
# yabai -m config mouse_action2                resize
# yabai -m config mouse_drop_action            swap

# Space Settings
yabai -m config layout                       bsp
yabai -m config top_padding                  14
yabai -m config bottom_padding               14
yabai -m config left_padding                 14
yabai -m config right_padding                14
yabai -m config window_gap                   14

# External Bar
yabai -m config external_bar main:35:0

# -----------------------
# Signals
# -----------------------
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus &> /dev/null"